// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelRequestWF.Infrastructure.Data;

#nullable disable

namespace TravelRequestWF.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812014713_RequestDocumentRestrictDelete")]
    partial class RequestDocumentRestrictDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TravelRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestDocumentId");

                    b.HasIndex("TravelRequestId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuperiorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuperiorId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.RequestDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelRequestId");

                    b.ToTable("RequestDocuments");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.TravelRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TravelRequests");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("TravelRequestWF.Infrastructure.Entities.RequestDocument", "RequestDocument")
                        .WithMany()
                        .HasForeignKey("RequestDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelRequestWF.Infrastructure.Entities.TravelRequest", "TravelRequest")
                        .WithMany("AuditLog")
                        .HasForeignKey("TravelRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequestDocument");

                    b.Navigation("TravelRequest");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.Employee", b =>
                {
                    b.HasOne("TravelRequestWF.Infrastructure.Entities.Employee", "Superior")
                        .WithMany("Subordinates")
                        .HasForeignKey("SuperiorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.RequestDocument", b =>
                {
                    b.HasOne("TravelRequestWF.Infrastructure.Entities.TravelRequest", "TravelRequest")
                        .WithMany("Documents")
                        .HasForeignKey("TravelRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TravelRequest");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.TravelRequest", b =>
                {
                    b.HasOne("TravelRequestWF.Infrastructure.Entities.Employee", "Approver")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRequestWF.Infrastructure.Entities.Employee", "Employee")
                        .WithMany("TravelRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.Employee", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("Subordinates");

                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("TravelRequestWF.Infrastructure.Entities.TravelRequest", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
